on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: Install Poetry
        run: pip install poetry==1.3.0
      - uses: actions/checkout@v3
      - run: poetry install
      - name: Check coding standards
        run: |
          poetry run black --check src/
          poetry run mypy src/

  test:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: Install Poetry
        run: pip install poetry==1.3.0
      - uses: actions/checkout@v3
      - run: poetry install
      - name: Run tests
        run: poetry run pytest src/
